#!/bin/sh
# Docker compose wrapper

help() {
  echo "Usage: dc [u|h] (or any docker compose command)"
  echo "  -u     up -d"
  echo "  -h     help"
  exit 1
}

get_command() {
  if docker compose >/dev/null 2>&1; then
    echo "docker compose"
    return
  fi

  if docker-compose >/dev/null 2>&1; then
    echo "docker-compose"
    return
  fi

  exit 1
}

up() {
  $(get_command) up -d --remove-orphans
}

pass_through() {
  $(get_command) "$@"
}

main() {
  case $1 in
    --up | -u | u)
      up
      ;;
    --help | -h | h)
      help
      ;;
    *)
      pass_through "$@"
      ;;
  esac
}

main "$@"
