#!/bin/sh
# Create and persitent dev container

get_container_name() {
  image_name=$(echo "$1" | tr -dc '[:alnum:]')
  echo "devc-$image_name"
}

create_image() {
  docker image inspect "$name" >/dev/null 2>&1 && return 0
  docker pull "$1"
  docker tag "$1" "$name"
}

start_container() {
  if [ -z "$(docker ps -a --filter "name=$name" --format "{{.Names}}")" ]; then
    docker run --name "$name" -itd "$name" /bin/sh
  fi
}

enter_container() {
  shell=$(docker exec "$name" echo "$SHELL")
  docker exec -it "$name" "$shell"
}

commit() {
  docker commit "$name" "$name"
  docker rm -f "$name"
}

main() {
  name=$(get_container_name "$1")
  create_image "$1"
  start_container
  enter_container
  commit
}

main "$@"
