#!/usr/bin/env sh
# mnm - minimalist Note manager

config_path="$HOME/.config/mnm/mnm.conf"

# Read config
#
read_config() {
  if [ -f "$config_path" ]; then
    # shellcheck source=../home/mnm/.config/mnm/mnm.conf
    . "$config_path"
  else
    echo "Config file not found"
    exit 1
  fi

  for directory in $directories; do
    [ -d "$path/$directory" ] || mkdir -p "$path/$directory" 2>/dev/null
  done
}

# Hep text
#
help() {
  echo "usage: n [-h] [-c]"
  echo "  -h      display help"
  echo "  -c      create note to a selected folder"
  echo "  -s      search all notes, and open selected one"
  echo "  -d      search notes in directory, and open selected one"
  exit 1
}

# Create note
#
open_markdown_file() {
  mkdir -p "$1"
  file_path="$1"/README.md
  {
    echo "---"
    echo "date: $(date "+%Y-%m-%d %H:%M:%S")"
    echo "tags: "
    echo "---"
    printf "\n"
    echo "# "
  } >"$file_path"
  $EDITOR "$file_path"
}

create_note() {
  directory=$(echo "$directories" | tr " " "\n" | fzf)
  if [ $? -eq 130 ]; then
    exit 0
  fi
  note_directory_name=$(date +%Y%m%d%H%M%S)
  note_path="$path/$directory/$note_directory_name"
  [ ! -f "$note_path" ] && open_markdown_file "$note_path"
}

# Search all notes or in directory
#
search_in_path() {
  found_file_path=$(rg '' "$1" | fzf --delimiter=/ --with-nth -1 | cut -d":" -f1)
  [ -z "$found_file_path" ] && exit 1
  $EDITOR "$found_file_path"
}

search_note() {
  search_in_path "$path"
}

search_directory() {
  directory=$(echo "$directories" | tr " " "\n" | fzf)
  search_in_path "$path/$directory"
}

index() {
  read_me_path="$path/README.md"
  echo "# Notes" >"$read_me_path"
  printf "\n" >>"$read_me_path"

  for directory in $directories; do
    if [ "$directory" = "daily" ]; then
      continue
    fi

    for note in "$path/$directory"/*; do
      link_title=$(grep -m 1 -o -e "# .*" "$note"/README.md | cut -d" " -f2-)
      id=$(echo "$note" | rev | cut -d"/" -f1 | rev)
      row="- $id - [$link_title]($directory/$id/README.md)"
      echo "$row" >>"$read_me_path"
    done
  done
}

main() {
  read_config
  case $1 in
    --help|-h|h)
      help
      ;;
    --create|-c|c)
      create_note
      ;;
    --search|-s|s)
      search_note
      ;;
    --dir_search|-d|d)
      search_directory
      ;;
    --index|-i|i)
      index
      ;;
    *)
      create_note
      ;;
  esac

  exit 0
}

main "$1"
