#!/bin/sh
# Save and push changes to git

main() {
  git add .
  git stash push -m "save"
  git pull
  git stash apply stash^"{/save}"
  git stash drop save
  git add .
  if [ -n "$*" ]; then
    git commit -m "$*"
  else
    git commit -m "$(git diff --name-only --staged | tr '\n' ' ')"
  fi
  git push
}


main "$@"
