#!/bin/sh
# Tmux attach or create session

tmux_session_name=$(tmux display-message -p '#S')

if [ "$1" ]; then
    session_name="$1"
elif [ "$tmux_session_name" ]; then
    session_name=$tmux_session_name
else
    session_name="$(basename "$(pwd)")"
fi

if [ "$session_name" = "$(whoami)" ]; then
    session_name="home"
fi

tmux attach 2> /dev/null  \
    || tmux new-session -s "$session_name" 2> /dev/null \
    || tmux new-session -s "$session_name" -d 2> /dev/null \
    ; tmux switch-client -t "$session_name" 2> /dev/null 
