---
- name: run debian tasks
  ansible.builtin.import_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - cht.sh
    - install
    - cli

- name: create config directory
  ansible.builtin.file:
    path: ~/.config/cht.sh
    state: directory
  tags:
    - cht.sh
    - link
    - cli

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/cht.sh/"
    dest: ~/.config/cht.sh
    state: link
    force: yes
  tags:
    - cht.sh
    - link
    - cli
