#!/usr/bin/env bash
# Run php in container

main() {
  versions=(7.0 7.2 7.3 7.4 8.0 8.1 8.2)

  if [[ ${versions[*]} =~ (^|[[:space:]])"$1"($|[[:space:]]) ]]; then
    ver="$1"
    arguments=${*:2}
  else
    ver=8.1
    arguments=${*}
  fi

  docker run -it --rm --name my-running-php-script -v "$PWD":/usr/src/myapp -w /usr/src/myapp php:"$ver"-cli php "$arguments"
}

main "$@"
