#!/bin/sh
# Docker wrapper

help() {
  echo "Usage: dk [s|p] (or any docker command)"
  echo "  -s     stop all containers"
  echo "  -v     prune everything with volumes"
  exit 0
}

stop() {
  docker ps -aq | xargs docker stop
}

prune() {
  docker system prune --all --volumes
}

pass_through() {
  docker "$@"
}

main() {
  case $1 in
    --stop | -s | s)
      stop
      ;;
    --prune | -p | p)
      prune
      ;;
    --help | -h | h)
      help
      ;;
    *)
      pass_through "$@"
      ;;
  esac
}

main "$@"
