#!/bin/sh
# mn - Add note

open_markdown_file() {
  note_directory_name=$(date +%Y%m%d%H%M%S)

  mkdir -p "$note_directory_name"
  file_path="$note_directory_name"/"$1".md

  {
    echo "---"
    echo "date: $(date "+%Y-%m-%d %H:%M:%S")"
    echo "tags: "
    echo "---"
    printf "\n"
    echo "# $2"
  } >"$file_path"
  $EDITOR "$file_path"
}

format_title() {
  echo "$1" | tr "[:upper:]" "[:lower:]" | tr -dc '[:alnum:]'
}

main() {
  echo "Enter note title: "
  read -r title
  formatted_title=$(format_title "$title")
  doc_title=$(echo "$title" | sed 's/\b\(.\)/\u\1/g')
  open_markdown_file "$formatted_title" "$doc_title"
}

main
