#!/bin/sh
# Switch wallpaper

gnome() {
  gsettings set org.gnome.desktop.background picture-uri "$(realpath "$1")"
}

main() {
  if [ -z "$1" ]; then
    echo "Usage: wa <path>"
    exit 1
  fi

  if command -v nitrogen >/dev/null 2>&1; then
    nitrogen --set-zoom-fill --save "$1"
    exit 0
  fi

  case "$DESKTOP_SESSION" in
    pop | gnome | ubuntu | ubuntu-xorg)
      gnome "$1"
      exit 0
      ;;
    *)
      echo "Unsupported desktop environment: $DESKTOP_SESSION"
      exit 1
      ;;
  esac
}

main "$1"
