---
- name: export NIXPKGS_ALLOW_UNFREE
  ansible.builtin.shell: export NIXPKGS_ALLOW_UNFREE=1

- name: install
  ansible.builtin.shell: nix-env -iA nixpkgs.starship

- name: install plugins
  ansible.builtin.shell: gh extension install "{{ item }}" --force
  loop:
    - github/gh-copilot
    - dlvhdr/gh-dash
