---
- name: run debian tasks
  ansible.builtin.import_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - github
    - install
    - cli

- name: check if copilot installed
  ansible.builtin.shell: "gh extension list | grep copilot"
  register: copilot_installed
  ignore_errors: yes
  changed_when: false
  tags:
    - github
    - install
    - cli

- name: check if dash installed
  ansible.builtin.shell: "gh extension list | grep dash"
  register: dash_installed
  ignore_errors: yes
  changed_when: false
  tags:
    - github
    - install
    - cli

- name: install gh plugins
  ansible.builtin.shell: gh extension install "{{ item }}" --force
  ignore_errors: yes
  loop:
    - github/gh-copilot
    - dlvhdr/gh-dash
  when: copilot_installed.rc != 0 or dash_installed.rc != 0
  tags:
    - github
    - install
    - cli
