---
- name: run debian tasks
  ansible.builtin.import_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - github
    - install
    - cli

- name: install gh plugins
  ansible.builtin.shell: gh extension install "{{ item }}" --force
  ignore_errors: yes
  loop:
    - github/gh-copilot
    - dlvhdr/gh-dash
  tags:
    - github
    - install
    - cli
