---
- name: install
  ansible.builtin.shell: ~/.nix-profile/bin/nix-env -iA nixpkgs.gh
  tags:
    - github
    - install
    - cli

- name: install plugins
  ansible.builtin.shell: ~/.nix-profile/bin/gh extension install "{{ item }}" --force
  loop:
    - github/gh-copilot
    - dlvhdr/gh-dash
  tags:
    - github
    - install
    - cli
