---
- name: add nodesource repository
  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_21.x | sudo -E bash
  become: yes

- name: install
  ansible.builtin.apt:
    name: nodejs
  become: yes
