---
- name: check if installed
  ansible.builtin.command: node --version
  register: nodejs_version
  ignore_errors: yes
  changed_when: false

- name: download installer
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/setup_22.x
    dest: "{{ tmp_dir }}/nodejs_setup_22.x"
  become: yes
  when: nodejs_version.rc != 0

- name: run installer
  ansible.builtin.script: "{{ tmp_dir }}/nodejs_setup_22.x"
  become: yes
  when: nodejs_version.rc != 0

- name: install nodejs
  ansible.builtin.apt:
    name: nsolid
    state: present
  become: yes
