---
- name: setup nodejs
  tags:
    - nodejs
    - link
    - cli
  block:
    - name: install
      ansible.builtin.import_tasks:
        file: debian.yml
      when: ansible_facts['os_family'] == 'Debian'
    - name: symlink config
      ansible.builtin.file:
        src: "{{ role_path }}/files/nodejs/.npmrc"
        dest: "{{ ansible_env.HOME }}/.npmrc"
        state: link
        force: yes
