---
- name: setup nodejs
  tags:
    - nodejs
    - install
    - cli
  block:
    - name: check if installed
      ansible.builtin.command: node --version
      register: nodejs_version
      ignore_errors: yes
      changed_when: false

    - name: run the install script
      ansible.builtin.shell: "{{ role_path }}/files/scripts/install"
      become: yes
      when: nodejs_version.rc != 0
