---
- name: install pipx and venv
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - pipx
    - python3-venv
  become: yes

- name: uv | install
  tags:
    - install
    - uv
    - cli
  block:
    - name: check if installed
      ansible.builtin.command: uv --version
      register: uv_version
      ignore_errors: yes
      changed_when: false

    - name: run the install script
      ansible.builtin.shell: bash roles/python/files/scripts/install
      become: yes
      when: uv_version.rc != 0
