---
- name: install
  tags:
    - python
    - install
    - cli
  block:
    - name: install
      ansible.builtin.import_tasks:
        file: debian.yml
      when: ansible_facts['os_family'] == 'Debian'
