#!/usr/bin/bash
# Get a colorscript from a pool

# pool=("zwaves" "tiefighter1row" "thebat2" "tanks" "space-invaders" "rally-x" "pacman" "guns" "dna" "darthvader" "blocks2" "square" "panes" "monster" "jangofett" "ghosts" "elfman" "crunch" "alpha")
main() {
  pool=("panes" "crunch" "alpha")
  colorscript -e "${pool[$RANDOM % ${#pool[@]}]}"
}

main
