#!/bin/sh
# List all scripts in ~/.local/bin/toolbox and their descriptions

main() {
  for script in ~/.local/bin/toolbox/*; do
    name=$(basename "$script")
    description=$(head -n 2 "$script" | tail -1)
    echo "$name $description"
  done
}

main
