---
- name: install
  ansible.builtin.shell:  "{{ nix_env_path }} -iA nixpkgs.{{ item }}"
  loop:
    - mysql
    - mycli
  tags:
    - mysql
    - install
    - cli

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/mycli/.myclirc"
    dest: ~/.myclirc
    state: link
  tags:
    - github
    - link
    - cli
