---
- name: run debian tasks
  ansible.builtin.import_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - mysql
    - install
    - cli

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/mycli/.myclirc"
    dest: ~/.myclirc
    state: link
  tags:
    - mysql
    - link
    - cli
