---
- name: create directory
  ansible.builtin.file:
    path: "{{ toolbox_bin_dir }}"
    state: directory
  tags:
    - toolbox
    - link
    - cli

- name: symlink scripts
  ansible.builtin.file:
    src: "{{ role_path }}/files/toolbox"
    dest: "{{ toolbox_bin_dir }}"
    state: link
    force: yes
  tags:
    - toolbox
    - link
    - cli

- name: symlink mnm config
  ansible.builtin.file:
    src: "{{ role_path }}/files/mnm"
    dest: ~/.config/mnm
    state: link
    force: yes
  tags:
    - toolbox
    - link
    - cli
