---
- name: create directory
  ansible.builtin.file:
    path: ~/.local/bin/toolbox
    state: directory
  tags:
    - toolbox
    - link
    - cli

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: ~/.local/bin/toolbox
    state: link
    force: yes
  tags:
    - toolbox
    - link
    - cli
