---
- name: install
  ansible.builtin.shell: ~/.nix-profile/bin/nix-env -iA nixpkgs.tmux
  tags:
    - tmux
    - install
    - cli

- name: symlink config
  ansible.builtin.file:
    path: ~/.config/tmux
    state: directory
  tags:
    - tmux
    - link
    - cli

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux"
    dest: ~/.config/tmux
    state: link
    force: yes
  tags:
    - tmux
    - link
    - cli
