#!/bin/sh
# Change default login shell

main() {
  shell=$(printf 'bash\nzsh' | fzf)

  echo "Current shell is $SHELL"

  if [ -n "$shell" ]; then
    chsh -s "$(which "$shell")" || exit 1
    echo "Default shell changed to $shell"
  fi

  echo "Logout and login again to see the changes"
}

main
