#!/bin/sh
# Docker compose wrapper

help() {
    echo "Usage: dc [u|h] (or any docker compose command)"
    echo "  -u     up -d"
    echo "  -h     help"
    exit 1
}

if type "docker-compose" > /dev/null 2>&1; then
    command="docker-compose"
fi

if type "docker compose" > /dev/null 2>&1; then
    command="docker compose"
fi

case $1 in
    u)
        exec $command up -d
        ;;
    h)
        help
        ;;
    *)
        exec $command "$@"
        ;;
esac
