#!/bin/sh

debian() {
  if apt >/dev/null 2>&1; then
    return
  fi

  if ! command -v ansible-playbook >/dev/null; then
    sudo apt update
    sudo apt install -y python3 python3-venv ansible
  fi

  exit 0
}

main() {
  debian
  echo "OS Family not supported."
  exit 1
}

main
