#!/usr/bin/env bash
# Tmux session manager

# Credit to ThePrimeagen

if [[ $# -eq 1 ]]; then
    selected=$1
else
    items=$(find ~/workspace -maxdepth 3 -mindepth 1 -type d)
    selected=$(echo "$items" | fzf)
fi

dirname=$(basename "$selected" | sed 's/\./_/g')

tmuxinator "$dirname" || tmux switch-client -t ="$dirname"

# shellcheck disable=2181
if [[ $? -eq 0 ]]; then
    exit 0
fi

# shellcheck disable=2015
tmux new-session -c "$selected" -d -s "$dirname" && tmux switch-client -t "$dirname" || tmux new -c "$selected" -A -s "$dirname"

