---
- name: install
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - curl
    - make
    - fzf
    - ripgrep
    - entr
    - imagemagick
    - translate-shell
    # - act
    # - hurl
    # - lazydocker
    # - lazygit
    - tmuxinator
    - ddgr
    - w3m
    - tldr
    - jq
    - ranger
  become: yes
