---
- name: download install script
  ansible.builtin.get_url:
    url: https://nixos.org/nix/install
    dest: "{{ tmp_dir }}/install-nix.sh"
  tags:
    - nix
    - install
    - global

- name: install
  ansible.builtin.script: "{{ tmp_dir }}/install-nix.sh --no-daemon"
  tags:
    - nix
    - install
    - global

- name: source nix profile
  ansible.builtin.script: ~/.nix-profile/etc/profile.d/nix.sh
  tags:
    - nix
    - install
    - global

- name: remove install script
  ansible.builtin.file:
    path: "{{ tmp_dir }}/install-nix.sh"
    state: absent
  tags:
    - nix
    - install
    - global
