---
- name: download install script
  ansible.builtin.get_url:
    url: https://nixos.org/nix/install
    dest: /tmp/install-nix.sh

- name: install
  ansible.builtin.script: /tmp/install-nix.sh --no-daemon

- name: source nix profile
  ansible.builtin.script: ~/.nix-profile/etc/profile.d/nix.sh

- name: remove install script
  ansible.builtin.file:
    path: /tmp/install-nix.sh
    state: absent
