---
- name: check if installed
  ansible.builtin.command: nix-env --version
  register: nix_env_version
  ignore_errors: yes
  changed_when: false
  tags:
    - nix
    - install
    - linux

- name: download install script
  ansible.builtin.get_url:
    url: https://nixos.org/nix/install
    dest: "{{ tmp_dir }}/install-nix.sh"
  when: nix_env_version.rc != 0
  tags:
    - nix
    - install
    - global

- name: install
  ansible.builtin.script: "{{ tmp_dir }}/install-nix.sh --no-daemon"
  when: nix_env_version.rc != 0
  tags:
    - nix
    - install
    - global
