---
- name: install nix
  tags:
    - nix
    - install
    - global
  block:
    - name: check if installed
      ansible.builtin.command: "{{ nix_env_path }} --version"
      register: nix_env_version
      ignore_errors: yes
      changed_when: false

    - name: download install script
      ansible.builtin.get_url:
        url: https://nixos.org/nix/install
        dest: "{{ tmp_dir }}/install-nix.sh"
      when: nix_env_version.rc != 0

    - name: install
      ansible.builtin.script: "{{ tmp_dir }}/install-nix.sh --no-daemon"
      when: nix_env_version.rc != 0
