---
- name: install nix
  tags:
    - nix
    - install
    - global
  block:
    - name: ensure curl is installed
      ansible.builtin.package:
        name: curl
        state: present
      become: true

    - name: download and install nix with daemon
      ansible.builtin.shell: "curl -L https://nixos.org/nix/install | sh -s"
      args:
        creates: "{{ nix_env_path }}"
      become: true
