---
- name: install nix
  tags:
    - nix
    - install
    - global
  block:
    - name: check if installed
      ansible.builtin.command: "{{ nix_env_path }} --version"
      register: nix_env_version
      ignore_errors: yes
      changed_when: false

    - name: ensure /nix directory exists
      ansible.builtin.file:
        path: /nix
        state: directory
        owner: "{{ ansible_env['USER'] }}"
        group: "{{ ansible_env['USER'] }}"
        mode: "0755"
      become: yes
      when: nix_env_version.rc != 0

    - name: install nix via shell/curl
      ansible.builtin.shell: "curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install | sh -s -- --no-daemon"
      when: nix_env_version.rc != 0
