---
- name: install
  tags:
    - hurl
    - install
    - cli
  block:
    - name: check if hurl is already installed
      ansible.builtin.command: hurl --version
      register: hurl_version
      ignore_errors: yes
      changed_when: false
    - name: download hurl .deb package
      ansible.builtin.get_url:
        url: "https://github.com/Orange-OpenSource/hurl/releases/download/6.1.1/hurl_6.1.1_amd64.deb"
        dest: "/tmp/hurl_6.1.1_amd64.deb"
        mode: '0644'
      when: hurl_version.rc != 0
    - name: install hurl .deb package
      ansible.builtin.apt:
        deb: "/tmp/hurl_6.1.1_amd64.deb"
        state: present
        update_cache: yes
      become: true
      when: hurl_version.rc != 0
