---
- name: run debian tasks
  ansible.builtin.import_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - starship
    - install
    - cli

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/starship/starship.toml"
    dest: ~/.config/starship.toml
    state: link
  tags:
    - starship
    - link
    - cli
