---
- name: install
  ansible.builtin.shell: nix-env -iA nixpkgs."{{ item }}"
  loop:
    - php82
    - php82Packages.composer
  tags:
    - php
    - install
    - cli

- name: symlink config
  ansible.builtin.file:
    path: ~/.config/phpactor
    state: directory
  tags:
    - php
    - link
    - cli

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/phpactor"
    dest: ~/.config/phpactor
    state: link
    force: yes
  tags:
    - php
    - link
    - cli
