---
- name: install
  tags:
    - php
    - install
    - cli
  block:
    - name: install
      ansible.builtin.import_tasks:
        file: debian.yml
      when: ansible_facts['os_family'] == 'Debian'
    - name: phpactor | create config directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/phpactor"
        state: directory

    - name: phpactor | symlink config
      ansible.builtin.file:
        src: "{{ role_path }}/files/phpactor"
        dest: "{{ ansible_env.HOME }}/.config/phpactor"
        state: link
        force: yes
