---
- name: run debian tasks
  ansible.builtin.import_tasks:
    file: debian.yml
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - php
    - install
    - cli

- name: phpactor | create config directory
  ansible.builtin.file:
    path: ~/.config/phpactor
    state: directory
  tags:
    - php
    - link
    - cli

- name: phpactor | symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/phpactor"
    dest: ~/.config/phpactor
    state: link
    force: yes
  tags:
    - php
    - link
    - cli
