---
- name: install
  ansible.builtin.shell: ~/.nix-profile/bin/nix-env -iA nixpkgs.neovim
  tags:
    - neovim
    - install
    - cli

- name: create directory
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory
  tags:
    - neovim
    - link
    - cli

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/nvim"
    dest: ~/.config/nvim
    state: link
    force: yes
  tags:
    - neovim
    - link
    - cli
