---
- name: install
  ansible.builtin.shell: nix-env -iA nixpkgs.neovim

- name: create directory
  ansible.builtin.file:
    path: ~/.config/nvim
    state: directory

- name: symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: ~/.config/nvim
    state: link
    force: yes
